// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTz3U2w8BVIjyByRfS66ENCpQJx5XLUYQ',
    appId: '1:290700951538:web:bd893780a9eec86c7fb56b',
    messagingSenderId: '290700951538',
    projectId: 'dateblue-gsu',
    authDomain: 'dateblue-gsu.firebaseapp.com',
    storageBucket: 'dateblue-gsu.firebasestorage.app',
    measurementId: 'G-WWY1FKRLQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzubBUfmxQmoGcpqJbyub7xJtOb_dcKDs',
    appId: '1:290700951538:android:987564a72805a06e7fb56b',
    messagingSenderId: '290700951538',
    projectId: 'dateblue-gsu',
    storageBucket: 'dateblue-gsu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdRSrnhhUSfODN_Qt2mDQytUobZuJyjj0',
    appId: '1:290700951538:ios:00dbe439c596ec9d7fb56b',
    messagingSenderId: '290700951538',
    projectId: 'dateblue-gsu',
    storageBucket: 'dateblue-gsu.firebasestorage.app',
    androidClientId: '290700951538-olmr3r2qk37ksad2sd4ku3soa83k7p0e.apps.googleusercontent.com',
    iosClientId: '290700951538-gcr6ea9r4rkjdgp2g1ckaqqhnb85eu2f.apps.googleusercontent.com',
    iosBundleId: 'edu.gsu.dateblue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdRSrnhhUSfODN_Qt2mDQytUobZuJyjj0',
    appId: '1:290700951538:ios:00dbe439c596ec9d7fb56b',
    messagingSenderId: '290700951538',
    projectId: 'dateblue-gsu',
    storageBucket: 'dateblue-gsu.firebasestorage.app',
    androidClientId: '290700951538-olmr3r2qk37ksad2sd4ku3soa83k7p0e.apps.googleusercontent.com',
    iosClientId: '290700951538-gcr6ea9r4rkjdgp2g1ckaqqhnb85eu2f.apps.googleusercontent.com',
    iosBundleId: 'edu.gsu.dateblue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTz3U2w8BVIjyByRfS66ENCpQJx5XLUYQ',
    appId: '1:290700951538:web:62eac6a24d0c36867fb56b',
    messagingSenderId: '290700951538',
    projectId: 'dateblue-gsu',
    authDomain: 'dateblue-gsu.firebaseapp.com',
    storageBucket: 'dateblue-gsu.firebasestorage.app',
    measurementId: 'G-LF4CLW5HC6',
  );
}
